CREATE TABLE CATEGORIA
  ( ID_CATEGORIA NUMBER (10) NOT NULL,
  	TITULO_CATEGORIA VARCHAR2(100) NOT NULL,
  	DESCRICAO_CATEGORIA VARCHAR2(255)
  ) ;
ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( ID_CATEGORIA ) ;


CREATE TABLE CONSUMIDOR
  (
    ID_CONSUMIDOR  NUMBER (10) NOT NULL ,
    NOME           VARCHAR2 (100) NOT NULL ,
    EMAIL          VARCHAR2 (100) NOT NULL ,
    SENHA          VARCHAR2 (100) NOT NULL ,
    ID_TIPO_ACESSO CHAR (1) NOT NULL ,
    KEY_ACESSO     VARCHAR2 (100)
  ) ;
ALTER TABLE CONSUMIDOR ADD CONSTRAINT CONSUMIDOR_PK PRIMARY KEY ( ID_CONSUMIDOR ) ;


CREATE TABLE EVENTOS_X_PRODUTOS
  (
    ID_LISTA             NUMBER (10) NOT NULL ,
    ID_PRODUTO           NUMBER (10) NOT NULL ,
    ID_CONSUMIDOR_ASSIGN NUMBER (10) NOT NULL ,
    QUANTIDADE           NUMBER (10) ,
    ID_UNIDADE_MEDIDA    NUMBER (10) NOT NULL
  ) ;
ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENTOS_X_PRODUTOS_PK PRIMARY KEY ( ID_LISTA, ID_PRODUTO ) ;


CREATE TABLE LISTAS
  (
    ID_LISTA      NUMBER (10) NOT NULL ,
    TIPO_LISTA    CHAR (1) NOT NULL ,
    TITULO        VARCHAR2 (100) ,
    ID_CONSUMIDOR NUMBER (10) NOT NULL,
    ATIVA         CHAR(1) NOT NULL,
    DATA_ICS      DATE NOT NULL,
    DATA_ALT      DATE NOT NULL
  ) ;
ALTER TABLE LISTAS ADD CONSTRAINT LISTAS_PK PRIMARY KEY ( ID_LISTA ) ;


CREATE TABLE LISTAS_EVENTOS
  ( ID_LISTA NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTAS_EVENTOS ADD CONSTRAINT LISTAS_EVENTOS_PK PRIMARY KEY ( ID_LISTA ) ;


CREATE TABLE LISTAS_PESSOAIS
  (
    ID_LISTA      NUMBER (10) NOT NULL ,
    COMPARTILHADA CHAR (1)
  ) ;
ALTER TABLE LISTAS_PESSOAIS ADD CONSTRAINT LISTAS_PESSOAIS_PK PRIMARY KEY ( ID_LISTA ) ;


CREATE TABLE LISTAS_X_PRODUTOS
  (
    ID_LISTA          NUMBER (10) NOT NULL ,
    ID_PRODUTO        NUMBER (10) NOT NULL ,
    QUANTIDADE        NUMBER (10) ,
    ID_UNIDADE_MEDIDA NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PRODUTOS_PK PRIMARY KEY ( ID_LISTA, ID_PRODUTO ) ;


CREATE TABLE LISTA_PESSOAS
  (
    ID_LISTA      NUMBER (10) NOT NULL ,
    ID_CONSUMIDOR NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTA_PESSOAS ADD CONSTRAINT LISTA_PESSOAS_PK PRIMARY KEY ( ID_CONSUMIDOR, ID_LISTA ) ;


CREATE TABLE OFERTAS
  (
    ID_OFERTA NUMBER (10) NOT NULL ,
    DESCRICAO VARCHAR2 (255) ,
    NOME      VARCHAR2 (100) ,
    IMAGEM BLOB ,
    ID_CONSUMIDOR NUMBER (10) NOT NULL,
    ATIVA         CHAR(1) NOT NULL
  ) ;
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_PK PRIMARY KEY ( ID_OFERTA ) ;


CREATE TABLE PRODUTOS
  (
    ID_PRODUTO   NUMBER (10) NOT NULL ,
    NOME         VARCHAR2 (100) ,
    DESCRICAO    VARCHAR2 (100) ,
    ID_CATEGORIA NUMBER (10) NOT NULL,
    ATIVO         CHAR(1) NOT NULL
  ) ;
ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS_PK PRIMARY KEY ( ID_PRODUTO ) ;


CREATE TABLE PRODUTO_CADASTRADO
  (
    ID_CONSUMIDOR NUMBER (10) NOT NULL ,
    ID_PRODUTO    NUMBER (10) NOT NULL ,
    DATA_ICS DATE NOT NULL
  ) ;
ALTER TABLE PRODUTO_CADASTRADO ADD CONSTRAINT PRODUTO_CADASTRADO_PK PRIMARY KEY ( ID_CONSUMIDOR, ID_PRODUTO ) ;


CREATE TABLE TIPO_ACESSO
  (
    ID_TIPO_ACESSO   CHAR (1) NOT NULL ,
    DESCRICAO_ACESSO VARCHAR2 (255) NOT NULL
  ) ;
ALTER TABLE TIPO_ACESSO ADD CONSTRAINT TIPO_ACESSO_PK PRIMARY KEY ( ID_TIPO_ACESSO ) ;


CREATE TABLE UNIDADE_MEDIDA
  (
    ID_UNIDADE_MEDIDA NUMBER (10) NOT NULL ,
    DESCRICAO_UNIDADE VARCHAR2 (100) NOT NULL,
    SIGLA VARCHAR2(10) NOT NULL,
    ATIVA         CHAR(1) NOT NULL
  ) ;
ALTER TABLE UNIDADE_MEDIDA ADD CONSTRAINT UNIDADE_MEDIDA_PK PRIMARY KEY ( ID_UNIDADE_MEDIDA ) ;


ALTER TABLE CONSUMIDOR ADD CONSTRAINT CONSUM_TIP_ACESSO_FK FOREIGN KEY ( ID_TIPO_ACESSO ) REFERENCES TIPO_ACESSO ( ID_TIPO_ACESSO ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENTOS_X_PROD_CONS_FK FOREIGN KEY ( ID_CONSUMIDOR_ASSIGN ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENT_X_PROD_LIST_EVENT_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS_EVENTOS ( ID_LISTA ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENT_X_PROD_PROD_FK FOREIGN KEY ( ID_PRODUTO ) REFERENCES PRODUTOS ( ID_PRODUTO ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENT_X_PROD_UNID_MED_FK FOREIGN KEY ( ID_UNIDADE_MEDIDA ) REFERENCES UNIDADE_MEDIDA ( ID_UNIDADE_MEDIDA ) ;

ALTER TABLE LISTAS ADD CONSTRAINT LISTAS_CONSUMIDOR_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE LISTAS_EVENTOS ADD CONSTRAINT LISTAS_EVENTOS_LISTAS_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS ( ID_LISTA ) ;

ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PROD_LISTAS_PES_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS_PESSOAIS ( ID_LISTA ) ;

ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PROD_PRODUTOS_FK FOREIGN KEY ( ID_PRODUTO ) REFERENCES PRODUTOS ( ID_PRODUTO ) ;

ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PROD_UNID_MEDIDA_FK FOREIGN KEY ( ID_UNIDADE_MEDIDA ) REFERENCES UNIDADE_MEDIDA ( ID_UNIDADE_MEDIDA ) ;

ALTER TABLE LISTA_PESSOAS ADD CONSTRAINT LIST_PESSOAS_CONS_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE LISTAS_PESSOAIS ADD CONSTRAINT LIST_PESSOAS_LIST_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS ( ID_LISTA ) ;

ALTER TABLE LISTA_PESSOAS ADD CONSTRAINT LIST_PESSOAS_LIST_FKv1 FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS ( ID_LISTA ) ;

ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_CONSUMIDOR_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS_CATEGORIA_FK FOREIGN KEY ( ID_CATEGORIA ) REFERENCES CATEGORIA ( ID_CATEGORIA ) ;

ALTER TABLE PRODUTO_CADASTRADO ADD CONSTRAINT PROD_CAD_CONSUMIDOR_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE PRODUTO_CADASTRADO ADD CONSTRAINT PROD_CAD_PRODUTOS_FK FOREIGN KEY ( ID_PRODUTO ) REFERENCES PRODUTOS ( ID_PRODUTO ) ;

ALTER TABLE CONSUMIDOR ADD CONSTRAINT EMAIL_UK UNIQUE (EMAIL);