INSERT INTO CATEGORIA (ID_CATEGORIA, TITULO_CATEGORIA, DESCRICAO_CATEGORIA) 
     VALUES (1, 'LIMPEZA', 'Produtos de limpeza');
INSERT INTO CATEGORIA (ID_CATEGORIA, TITULO_CATEGORIA, DESCRICAO_CATEGORIA) 
     VALUES (2, 'LIMPEZA', 'Produtos de limpeza');
INSERT INTO CATEGORIA (ID_CATEGORIA, TITULO_CATEGORIA, DESCRICAO_CATEGORIA) 
     VALUES (3, 'LIMPEZA', 'Produtos de limpeza');
INSERT INTO CATEGORIA (ID_CATEGORIA, TITULO_CATEGORIA, DESCRICAO_CATEGORIA) 
     VALUES (4, 'LIMPEZA', 'Produtos de limpeza');
INSERT INTO CATEGORIA (ID_CATEGORIA, TITULO_CATEGORIA, DESCRICAO_CATEGORIA) 
     VALUES (5, 'LIMPEZA', 'Produtos de limpeza');

INSERT INTO CONSUMIDOR (ID_CONSUMIDOR, NOME, EMAIL, SENHA, ID_TIPO_ACESSO, KEY_ACESSO) 
     VALUES (1, 'Mateus Sauer Govea', 'mateus.sauer@gmail.com', 'mateus', 'F', '39FUW9FUW9UR939ORU39RUORWU94UW9RU4');
INSERT INTO CONSUMIDOR (ID_CONSUMIDOR, NOME, EMAIL, SENHA, ID_TIPO_ACESSO, KEY_ACESSO) 
     VALUES ();
INSERT INTO CONSUMIDOR (ID_CONSUMIDOR, NOME, EMAIL, SENHA, ID_TIPO_ACESSO, KEY_ACESSO) 
     VALUES ();
INSERT INTO CONSUMIDOR (ID_CONSUMIDOR, NOME, EMAIL, SENHA, ID_TIPO_ACESSO, KEY_ACESSO) 
     VALUES ();
INSERT INTO CONSUMIDOR (ID_CONSUMIDOR, NOME, EMAIL, SENHA, ID_TIPO_ACESSO, KEY_ACESSO) 
     VALUES ();

INSERT INTO LISTAS (ID_LISTA, TIPO_LISTA, TITULO, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO LISTAS (ID_LISTA, TIPO_LISTA, TITULO, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO LISTAS (ID_LISTA, TIPO_LISTA, TITULO, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO LISTAS (ID_LISTA, TIPO_LISTA, TITULO, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO LISTAS (ID_LISTA, TIPO_LISTA, TITULO, ID_CONSUMIDOR, ATIVA) 
     VALUES ();

INSERT INTO LISTAS_EVENTOS (ID_LISTA) 
     VALUES ();
INSERT INTO LISTAS_EVENTOS (ID_LISTA) 
     VALUES ();
INSERT INTO LISTAS_EVENTOS (ID_LISTA) 
     VALUES ();
INSERT INTO LISTAS_EVENTOS (ID_LISTA) 
     VALUES ();
INSERT INTO LISTAS_EVENTOS (ID_LISTA) 
     VALUES ();

INSERT INTO LISTAS_PESSOAIS (ID_LISTA, COMPARTILHADA) 
     VALUES (1, 'Y');
INSERT INTO LISTAS_PESSOAIS (ID_LISTA, COMPARTILHADA) 
     VALUES (1, 'Y');
INSERT INTO LISTAS_PESSOAIS (ID_LISTA, COMPARTILHADA) 
     VALUES (1, 'Y');
INSERT INTO LISTAS_PESSOAIS (ID_LISTA, COMPARTILHADA) 
     VALUES (1, 'Y');
INSERT INTO LISTAS_PESSOAIS (ID_LISTA, COMPARTILHADA) 
     VALUES (1, 'Y');

INSERT INTO LISTAS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO LISTAS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO LISTAS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO LISTAS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO LISTAS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();

INSERT INTO LISTA_PESSOAS (ID_LISTA, ID_CONSUMIDOR) 
     VALUES ();
INSERT INTO LISTA_PESSOAS (ID_LISTA, ID_CONSUMIDOR) 
     VALUES ();
INSERT INTO LISTA_PESSOAS (ID_LISTA, ID_CONSUMIDOR) 
     VALUES ();
INSERT INTO LISTA_PESSOAS (ID_LISTA, ID_CONSUMIDOR) 
     VALUES ();
INSERT INTO LISTA_PESSOAS (ID_LISTA, ID_CONSUMIDOR) 
     VALUES ();

INSERT INTO OFERTAS (ID_OFERTA, DESCRICAO, NOME, IMAGEM, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO OFERTAS (ID_OFERTA, DESCRICAO, NOME, IMAGEM, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO OFERTAS (ID_OFERTA, DESCRICAO, NOME, IMAGEM, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO OFERTAS (ID_OFERTA, DESCRICAO, NOME, IMAGEM, ID_CONSUMIDOR, ATIVA) 
     VALUES ();
INSERT INTO OFERTAS (ID_OFERTA, DESCRICAO, NOME, IMAGEM, ID_CONSUMIDOR, ATIVA) 
     VALUES ();

INSERT INTO PRODUTOS (ID_PRODUTO, NOME, DESCRICAO, ID_CATEGORIA, ATIVO) 
     VALUES ();
INSERT INTO PRODUTOS (ID_PRODUTO, NOME, DESCRICAO, ID_CATEGORIA, ATIVO) 
     VALUES ();
INSERT INTO PRODUTOS (ID_PRODUTO, NOME, DESCRICAO, ID_CATEGORIA, ATIVO) 
     VALUES ();
INSERT INTO PRODUTOS (ID_PRODUTO, NOME, DESCRICAO, ID_CATEGORIA, ATIVO) 
     VALUES ();
INSERT INTO PRODUTOS (ID_PRODUTO, NOME, DESCRICAO, ID_CATEGORIA, ATIVO) 
     VALUES ();

INSERT INTO PRODUTO_CADASTRADO (ID_CONSUMIDOR, ID_PRODUTO, DATA_CADASTRO) 
     VALUES ();
INSERT INTO PRODUTO_CADASTRADO (ID_CONSUMIDOR, ID_PRODUTO, DATA_CADASTRO) 
     VALUES ();
INSERT INTO PRODUTO_CADASTRADO (ID_CONSUMIDOR, ID_PRODUTO, DATA_CADASTRO) 
     VALUES ();
INSERT INTO PRODUTO_CADASTRADO (ID_CONSUMIDOR, ID_PRODUTO, DATA_CADASTRO) 
     VALUES ();
INSERT INTO PRODUTO_CADASTRADO (ID_CONSUMIDOR, ID_PRODUTO, DATA_CADASTRO) 
     VALUES ();

INSERT INTO TIPO_ACESSO (ID_TIPO_ACESSO, DESCRICAO_ACESSO) 
     VALUES ();
INSERT INTO TIPO_ACESSO (ID_TIPO_ACESSO, DESCRICAO_ACESSO) 
     VALUES ();
INSERT INTO TIPO_ACESSO (ID_TIPO_ACESSO, DESCRICAO_ACESSO) 
     VALUES ();
INSERT INTO TIPO_ACESSO (ID_TIPO_ACESSO, DESCRICAO_ACESSO) 
     VALUES ();
INSERT INTO TIPO_ACESSO (ID_TIPO_ACESSO, DESCRICAO_ACESSO) 
     VALUES ();

INSERT INTO UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA, DESCRICAO_UNIDADE, ATIVA) 
     VALUES ();
INSERT INTO UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA, DESCRICAO_UNIDADE, ATIVA) 
     VALUES ();
INSERT INTO UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA, DESCRICAO_UNIDADE, ATIVA) 
     VALUES ();
INSERT INTO UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA, DESCRICAO_UNIDADE, ATIVA) 
     VALUES ();
INSERT INTO UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA, DESCRICAO_UNIDADE, ATIVA) 
     VALUES ();

INSERT INTO EVENTOS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, ID_CONSUMIDOR_ASSIGN, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO EVENTOS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, ID_CONSUMIDOR_ASSIGN, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO EVENTOS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, ID_CONSUMIDOR_ASSIGN, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO EVENTOS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, ID_CONSUMIDOR_ASSIGN, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();
INSERT INTO EVENTOS_X_PRODUTOS (ID_LISTA, ID_PRODUTO, ID_CONSUMIDOR_ASSIGN, QUANTIDADE, ID_UNIDADE_MEDIDA) 
     VALUES ();