CREATE OR REPLACE TRIGGER ALTERA_PRODUTOS
BEFORE INSERT OR UPDATE OR DELETE ON LISTAS_X_PRODUTOS
FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      UPDATE LISTAS
         SET DATA_ALT = SYSDATE
       WHERE ID_LISTA = :NEW.ID_LISTA;
    WHEN UPDATING THEN
      UPDATE LISTAS
         SET DATA_ALT = SYSDATE
       WHERE ID_LISTA = :NEW.ID_LISTA;
   WHEN DELETING THEN
      UPDATE LISTAS
         SET DATA_ALT = SYSDATE
       WHERE ID_LISTA = :OLD.ID_LISTA;
  END CASE;
END;
