CREATE OR REPLACE VIEW PRODUTOS_DA_LISTA 
AS
  SELECT PROD.ID_PRODUTO,
         PROD.NOME,
         PROD.DESCRICAO,
         PROD.ID_CATEGORIA,
         PROD.ATIVO,
         LISTPROD.ID_LISTA,
         LISTPROD.QUANTIDADE,
         LISTPROD.ID_UNIDADE_MEDIDA
    FROM PRODUTOS PROD,
         LISTAS_X_PRODUTOS LISTPROD
   WHERE PROD.ID_PRODUTO = LISTPROD.ID_PRODUTO;