-- Gerado por Oracle SQL Developer Data Modeler 4.1.5.907
--   em:        2016-10-27 18:00:45 BRST
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE CATEGORIA
  ( ID_CATEGORIA NUMBER (10) NOT NULL
  ) ;
ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( ID_CATEGORIA ) ;


CREATE TABLE CONSUMIDOR
  (
    ID_CONSUMIDOR  NUMBER (10) NOT NULL ,
    NOME           VARCHAR2 (100) NOT NULL ,
    EMAIL          VARCHAR2 (100) NOT NULL ,
    SENHA          VARCHAR2 (100) NOT NULL ,
    ID_TIPO_ACESSO CHAR (1) NOT NULL ,
    KEY_ACESSO     NUMBER (10)
  ) ;
ALTER TABLE CONSUMIDOR ADD CONSTRAINT CONSUMIDOR_PK PRIMARY KEY ( ID_CONSUMIDOR ) ;


CREATE TABLE EVENTOS_X_PRODUTOS
  (
    ID_LISTA             NUMBER (10) NOT NULL ,
    ID_PRODUTO           NUMBER (10) NOT NULL ,
    ID_CONSUMIDOR_ASSIGN NUMBER (10) NOT NULL ,
    QUANTIDADE           NUMBER (10) ,
    ID_UNIDADE_MEDIDA    NUMBER (10) NOT NULL
  ) ;
ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENTOS_X_PRODUTOS_PK PRIMARY KEY ( ID_LISTA, ID_PRODUTO ) ;


CREATE TABLE LISTAS
  (
    ID_LISTA      NUMBER (10) NOT NULL ,
    TIPO_LISTA    CHAR (1) NOT NULL ,
    TITULO        VARCHAR2 (100) ,
    ID_CONSUMIDOR NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTAS ADD CONSTRAINT LISTAS_PK PRIMARY KEY ( ID_LISTA ) ;


CREATE TABLE LISTAS_EVENTOS
  ( ID_LISTA NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTAS_EVENTOS ADD CONSTRAINT LISTAS_EVENTOS_PK PRIMARY KEY ( ID_LISTA ) ;


CREATE TABLE LISTAS_PESSOAS
  (
    ID_LISTA      NUMBER (10) NOT NULL ,
    COMPARTILHADA CHAR (1)
  ) ;
ALTER TABLE LISTAS_PESSOAS ADD CONSTRAINT LISTAS_PESSOAS_PK PRIMARY KEY ( ID_LISTA ) ;


CREATE TABLE LISTAS_X_PRODUTOS
  (
    ID_LISTA          NUMBER (10) NOT NULL ,
    ID_PRODUTO        NUMBER (10) NOT NULL ,
    QUANTIDADE        NUMBER (10) ,
    ID_UNIDADE_MEDIDA NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PRODUTOS_PK PRIMARY KEY ( ID_LISTA, ID_PRODUTO ) ;


CREATE TABLE LISTA_PESSOAS
  (
    ID_LISTA      NUMBER (10) NOT NULL ,
    ID_CONSUMIDOR NUMBER (10) NOT NULL
  ) ;
ALTER TABLE LISTA_PESSOAS ADD CONSTRAINT LISTA_PESSOAS_PK PRIMARY KEY ( ID_CONSUMIDOR, ID_LISTA ) ;


CREATE TABLE OFERTAS
  (
    ID_OFERTA NUMBER (10) NOT NULL ,
    DESCRICAO VARCHAR2 (255) ,
    NOME      VARCHAR2 (100) ,
    IMAGEM BLOB ,
    ID_CONSUMIDOR NUMBER (100) NOT NULL
  ) ;
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_PK PRIMARY KEY ( ID_OFERTA ) ;


CREATE TABLE PRODUTOS
  (
    ID_PRODUTO   NUMBER (10) NOT NULL ,
    NOME         VARCHAR2 (100) ,
    DESCRICAO    VARCHAR2 (100) ,
    ID_CATEGORIA NUMBER (10) NOT NULL
  ) ;
ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS_PK PRIMARY KEY ( ID_PRODUTO ) ;


CREATE TABLE PRODUTO_CADASTRADO
  (
    ID_CONSUMIDOR NUMBER (10) NOT NULL ,
    ID_PRODUTO    NUMBER (10) NOT NULL ,
    DATA_CADASTRO DATE NOT NULL
  ) ;
ALTER TABLE PRODUTO_CADASTRADO ADD CONSTRAINT PRODUTO_CADASTRADO_PK PRIMARY KEY ( ID_CONSUMIDOR, ID_PRODUTO ) ;


CREATE TABLE TIPO_ACESSO
  (
    ID_TIPO_ACESSO   CHAR (1) NOT NULL ,
    DESCRICAO_ACESSO VARCHAR2 (255) NOT NULL
  ) ;
ALTER TABLE TIPO_ACESSO ADD CONSTRAINT TIPO_ACESSO_PK PRIMARY KEY ( ID_TIPO_ACESSO ) ;


CREATE TABLE UNIDADE_MEDIDA
  (
    ID_UNIDADE_MEDIDA NUMBER (10) NOT NULL ,
    DESCRICAO_UNIDADE VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE UNIDADE_MEDIDA ADD CONSTRAINT UNIDADE_MEDIDA_PK PRIMARY KEY ( ID_UNIDADE_MEDIDA ) ;


ALTER TABLE CONSUMIDOR ADD CONSTRAINT CONSUM_TIP_ACESSO_FK FOREIGN KEY ( ID_TIPO_ACESSO ) REFERENCES TIPO_ACESSO ( ID_TIPO_ACESSO ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENTOS_X_PROD_CONS_FK FOREIGN KEY ( ID_CONSUMIDOR_ASSIGN ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENT_X_PROD_LIST_EVENT_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS_EVENTOS ( ID_LISTA ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENT_X_PROD_PROD_FK FOREIGN KEY ( ID_PRODUTO ) REFERENCES PRODUTOS ( ID_PRODUTO ) ;

ALTER TABLE EVENTOS_X_PRODUTOS ADD CONSTRAINT EVENT_X_PROD_UNID_MED_FK FOREIGN KEY ( ID_UNIDADE_MEDIDA ) REFERENCES UNIDADE_MEDIDA ( ID_UNIDADE_MEDIDA ) ;

ALTER TABLE LISTAS ADD CONSTRAINT LISTAS_CONSUMIDOR_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE LISTAS_EVENTOS ADD CONSTRAINT LISTAS_EVENTOS_LISTAS_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS ( ID_LISTA ) ;

ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PROD_LISTAS_PES_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS_PESSOAS ( ID_LISTA ) ;

ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PROD_PRODUTOS_FK FOREIGN KEY ( ID_PRODUTO ) REFERENCES PRODUTOS ( ID_PRODUTO ) ;

ALTER TABLE LISTAS_X_PRODUTOS ADD CONSTRAINT LISTAS_X_PROD_UNID_MEDIDA_FK FOREIGN KEY ( ID_UNIDADE_MEDIDA ) REFERENCES UNIDADE_MEDIDA ( ID_UNIDADE_MEDIDA ) ;

ALTER TABLE LISTA_PESSOAS ADD CONSTRAINT LIST_PESSOAS_CONS_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE LISTAS_PESSOAS ADD CONSTRAINT LIST_PESSOAS_LIST_FK FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS ( ID_LISTA ) ;

ALTER TABLE LISTA_PESSOAS ADD CONSTRAINT LIST_PESSOAS_LIST_FKv1 FOREIGN KEY ( ID_LISTA ) REFERENCES LISTAS ( ID_LISTA ) ;

ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_CONSUMIDOR_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS_CATEGORIA_FK FOREIGN KEY ( ID_CATEGORIA ) REFERENCES CATEGORIA ( ID_CATEGORIA ) ;

ALTER TABLE PRODUTO_CADASTRADO ADD CONSTRAINT PROD_CAD_CONSUMIDOR_FK FOREIGN KEY ( ID_CONSUMIDOR ) REFERENCES CONSUMIDOR ( ID_CONSUMIDOR ) ;

ALTER TABLE PRODUTO_CADASTRADO ADD CONSTRAINT PROD_CAD_PRODUTOS_FK FOREIGN KEY ( ID_PRODUTO ) REFERENCES PRODUTOS ( ID_PRODUTO ) ;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
